# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipums2db < Formula
  desc "Convert IPUMS data extracts to database dump files"
  homepage "https://github.com/rhawrami/ipums2db"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rhawrami/ipums2db/releases/download/v1.0.1/ipums2db_Darwin_x86_64.tar.gz"
      sha256 "75c2db610f3b0c9ee5478cc2259d69546fb18ce1ce19aa913f50008a222a7eca"

      def install
        bin.install "ipums2db"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rhawrami/ipums2db/releases/download/v1.0.1/ipums2db_Darwin_arm64.tar.gz"
      sha256 "cd5de3bffcf1856e4288bf56eda1763c1c949fd42ff5561e6147e5086baf21b0"

      def install
        bin.install "ipums2db"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rhawrami/ipums2db/releases/download/v1.0.1/ipums2db_Linux_x86_64.tar.gz"
      sha256 "04acc662b72c2b03cb19edae3f6d2684a787006501aa6d5dff06e0c60c7ae0da"
      def install
        bin.install "ipums2db"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rhawrami/ipums2db/releases/download/v1.0.1/ipums2db_Linux_arm64.tar.gz"
      sha256 "d3965a9c0ad01df0cebf9fe2bc67489b2da41eb29147ba8b296d1034db96bf4e"
      def install
        bin.install "ipums2db"
      end
    end
  end

  test do
    system "#{bin}/ipums2db --help"
  end
end
